# Generated by Django 2.0.1 on 2018-01-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Represents url category name', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('item_id', models.CharField(help_text='Represents url item ID', max_length=20)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Category')),
            ],
        ),
    ]
