# Generated by Django 2.0.3 on 2018-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.Subcategory'),
        ),
    ]
