# Generated by Django 2.0.3 on 2018-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180322_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
