# Generated by Django 2.0.3 on 2018-03-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertiesKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPropertiesValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductPropertiesKeys')),
            ],
        ),
        migrations.RemoveField(
            model_name='productproperties',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductProperties',
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(to='product.ProductPropertiesValues'),
        ),
    ]
