# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hn_parser', '0002_auto_20180213_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
