# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_deadline',
            field=models.DateField(verbose_name='Deadline date'),
        ),
    ]
