# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180211_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
