# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='descendants',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='kids',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.TextField(default='', null=True),
        ),
    ]
