# Generated by Django 2.0.1 on 2018-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('text', models.TextField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beststories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
                ('text', models.TextField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
                ('text', models.TextField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Showstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.IntegerField()),
                ('rec_type', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('by', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.URLField(null=True)),
                ('text', models.TextField(null=True)),
                ('descendants', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
