# Generated by Django 2.0.1 on 2018-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askstories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beststories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='beststories',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobstories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobstories',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newstories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newstories',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='showstories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='showstories',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
